# Generated by Django 4.0.5 on 2022-07-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERMISOS',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='TIPO_USUARIO',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_cliente',
            new_name='id_usuario',
        ),
        migrations.DeleteModel(
            name='PRODUCTO',
        ),
        migrations.DeleteModel(
            name='TIPO_PRODUCTO',
        ),
        migrations.AddField(
            model_name='tipo_usuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
        ),
    ]
