# Generated by Django 4.0.5 on 2022-07-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_permisos_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
