# Generated by Django 4.0.5 on 2022-07-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_contraseña_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_usuario'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
