# Generated by Django 4.0.5 on 2022-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tipo_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(default='usuario', max_length=255),
        ),
        migrations.DeleteModel(
            name='PERMISOS',
        ),
        migrations.DeleteModel(
            name='TIPO_USUARIO',
        ),
    ]
